# .github/workflows/onchain-sol.yml
name: On-chain SOL — Diário

on:
  schedule:
    - cron: "15 9 * * *"   # 06:15 BRT
    - cron: "30 9 * * *"   # 06:30 BRT
    - cron: "45 9 * * *"   # 06:45 BRT
    - cron: "0 10 * * *"   # 07:00 BRT
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Sanity check secrets
        run: |
          [[ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]] || { echo "Missing TELEGRAM_BOT_TOKEN"; exit 1; }
          [[ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]]   || { echo "Missing TELEGRAM_CHAT_ID"; exit 1; }
          [[ -n "${{ secrets.GROQ_API_KEY }}" ]]       || echo "Warn: GROQ_API_KEY empty"

      - name: Compute stamp (SOL daily) & check
        id: gate
        run: |
          mkdir -p .sent
          STAMP=".sent/done-sol-daily-$(date -u +%F)"
          echo "stamp=$STAMP" >> $GITHUB_OUTPUT
          if [[ -f "$STAMP" ]]; then
            echo "skip=true"  >> $GITHUB_OUTPUT
            echo "Already sent today (stamp: $STAMP). Skipping."
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Send on-chain SOL (daily)
        if: steps.gate.outputs.skip != 'true'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          SOL_TELEGRAM_CHAT_ID:  ${{ secrets.SOL_TELEGRAM_CHAT_ID }}
          SOL_TELEGRAM_TOPIC_ID: ${{ secrets.SOL_TELEGRAM_TOPIC_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python onchain_to_telegram_sol.py --provider groq --model llama-3.1-70b-versatile --send-as message --period daily

      - name: Create stamp file
        if: steps.gate.outputs.skip != 'true'
        run: |
          touch "${{ steps.gate.outputs.stamp }}"

      - name: Commit counters & stamp
        if: steps.gate.outputs.skip != 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add counters.json "${{ steps.gate.outputs.stamp }}" || true
          if ! git diff --cached --quiet; then
            git commit -m "SOL diário: update counters & .sent [skip ci]"
            git push
          fi
