name: On-chain SOL — Mensal

on:
  schedule:
    - cron: "10 10 1 * *"  # dia 1, 07:10 BRT
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Sanity check secrets
        run: |
          [[ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]] || { echo "Missing TELEGRAM_BOT_TOKEN"; exit 1; }
          [[ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]] || { echo "Missing TELEGRAM_CHAT_ID"; exit 1; }
          [[ -n "${{ secrets.GROQ_API_KEY }}" ]] || echo "Warn: GROQ_API_KEY empty (use outro provider ou defina o secret)"

      - name: Send on-chain SOL (monthly)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          SOL_TELEGRAM_CHAT_ID:  ${{ secrets.SOL_TELEGRAM_CHAT_ID }}   # opcional
          SOL_TELEGRAM_TOPIC_ID: ${{ secrets.SOL_TELEGRAM_TOPIC_ID }}  # opcional
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python onchain_to_telegram_sol.py --provider groq --model llama-3.1-70b-versatile --send-as message --period monthly

      - name: Commit counters
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add counters.json || true
          if ! git diff --cached --quiet; then
            git commit -m "SOL mensal: update counters [skip ci]"
            git push
          fi
