name: On-chain SOL — Diário

on:
  schedule:
    - cron: "15 9 * * *"   # 06:15 BRT
    - cron: "30 9 * * *"   # 06:30 BRT
    - cron: "45 9 * * *"   # 06:45 BRT
    - cron: "0 10 * * *"   # 07:00 BRT
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Sanity check secrets
        run: |
          [[ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]] || { echo "Missing TELEGRAM_BOT_TOKEN"; exit 1; }
          [[ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]]   || { echo "Missing TELEGRAM_CHAT_ID"; exit 1; }

      # Hotfix: se a linha do 'corpo' tiver sido truncada, corrige antes de rodar
      - name: Hotfix (linha do corpo SOL)
        run: |
          python - <<'PY'
          import re, pathlib
          p = pathlib.Path("onchain_to_telegram_sol.py")
          s = p.read_text(encoding="utf-8")
          if "if content:" not in s or "fallback_content(data_str, numero, motivo, label)" not in s:
              s2 = re.sub(
                  r"(?m)^(\s*)corpo\s*=.*$",
                  r"""\1if content:
\1    corpo = content.strip()
\1else:
\1    corpo = fallback_content(data_str, numero, motivo, label)""",
                  s, count=1
              )
              if s2 != s:
                  p.write_text(s2, encoding="utf-8")
                  print("Hotfix aplicado.")
              else:
                  print("Hotfix não necessário (nenhuma linha 'corpo =' encontrada).")
          else:
              print("Bloco do corpo já está correto.")
          PY

      - name: Syntax check (SOL)
        run: |
          python -m py_compile onchain_to_telegram_sol.py

      - name: Send on-chain SOL (daily)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          # opcionais se quiser separar por grupo/tópico:
          SOL_TELEGRAM_CHAT_ID:  ${{ secrets.SOL_TELEGRAM_CHAT_ID }}
          SOL_TELEGRAM_TOPIC_ID: ${{ secrets.SOL_TELEGRAM_TOPIC_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python onchain_to_telegram_sol.py --provider groq --model llama-3.1-70b-versatile --send-as message --period daily

      - name: Commit counters
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add counters.json || true
          if ! git diff --cached --quiet; then
            git commit -m "SOL diário: update counters [skip ci]"
            git push
          fi
