name: On-chain watchdog semanal (garantia)

on:
  schedule:
    - cron: "20 10 * * 1"   # 07:20 BRT (UTC-3)
    - cron: "30 10 * * 1"   # backup 07:30 BRT
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

concurrency:
  group: watchdog-semanal
  cancel-in-progress: false

jobs:
  watchdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute this week (BRT) & sentinel
        id: meta
        run: |
          WEEK=$(TZ=America/Sao_Paulo date +%G-W%V)     # ex: 2025-W37
          SENT=".sent/done-weekly-${WEEK}"
          echo "sent=${SENT}" >> $GITHUB_OUTPUT
          echo "week=${WEEK}"

      - name: Need to trigger?
        id: need
        run: |
          if [ -f "${{ steps.meta.outputs.sent }}" ]; then
            echo "need=false" >> $GITHUB_OUTPUT
            echo "Weekly already sent."
          else
            echo "need=true" >> $GITHUB_OUTPUT
            echo "Weekly NOT sent yet."
          fi

      - name: Trigger onchain-weekly.yml
        if: steps.need.outputs.need == 'true'
        env:
          OWNER_REPO: ${{ github.repository }}
        run: |
          set -e
          curl -s -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${OWNER_REPO}/actions/workflows/onchain-weekly.yml/dispatches \
            -d '{"ref":"main"}'
          echo "Dispatched onchain-weekly.yml"
