name: On-chain watchdog mensal (garantia)

on:
  schedule:
    - cron: "25 10 1 * *"   # 07:25 BRT
    - cron: "35 10 1 * *"   # backup 07:35 BRT
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

concurrency:
  group: watchdog-mensal
  cancel-in-progress: false

jobs:
  watchdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute this month (BRT) & sentinel
        id: meta
        run: |
          MONTH=$(TZ=America/Sao_Paulo date +%Y-%m)     # ex: 2025-09
          SENT=".sent/done-monthly-${MONTH}"
          echo "sent=${SENT}" >> $GITHUB_OUTPUT
          echo "month=${MONTH}"

      - name: Need to trigger?
        id: need
        run: |
          if [ -f "${{ steps.meta.outputs.sent }}" ]; then
            echo "need=false" >> $GITHUB_OUTPUT
            echo "Monthly already sent."
          else
            echo "need=true" >> $GITHUB_OUTPUT
            echo "Monthly NOT sent yet."
          fi

      - name: Trigger onchain-monthly.yml
        if: steps.need.outputs.need == 'true'
        env:
          OWNER_REPO: ${{ github.repository }}
        run: |
          set -e
          curl -s -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${OWNER_REPO}/actions/workflows/onchain-monthly.yml/dispatches \
            -d '{"ref":"main"}'
          echo "Dispatched onchain-monthly.yml"
